# Generated by Django 3.2.5 on 2021-08-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
