# Generated by Django 3.2.5 on 2021-08-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_auto_20210802_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
