# Generated by Django 3.2.5 on 2021-08-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0004_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
    ]
